### ISSUE TITLE
Cannot run discovery.py on mac (wifi or eth) - Can't assign requested address

### ISSUE THREAD

**Issue by lyricnz** [philippechataignon/smrt#3]
Should discovery work on wifi?

```
❯ python3 ./discovery.py -i en0
Traceback (most recent call last):
  File "/Users/simonroberts/src/github/philippechataignon/smrt/./discovery.py", line 47, in <module>
    main()
  File "/Users/simonroberts/src/github/philippechataignon/smrt/./discovery.py", line 33, in main
    switches = discover_switches(args.interface)
  File "/Users/simonroberts/src/github/philippechataignon/smrt/./discovery.py", line 14, in discover_switches
    net = Network(interface)
  File "/Users/simonroberts/src/github/philippechataignon/smrt/network.py", line 64, in __init__
    self.rs.bind((Network.BROADCAST_ADDR, Network.UDP_RECEIVE_FROM_PORT))
OSError: [Errno 49] Can't assign requested address
```

System is 

```
❯ uname -a
Darwin simonmac.roberts 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64
```

Ventura 13.1 (22C65)

I guess I don't know **how** this works - was assuming it was either via web-scraping, or some magic API. Will try on a real linux box.

**Comment by lyricnz** [comment]
Worked fine on a linux box. Which limitation am I hitting?

**Comment by lyricnz** [comment]
Doesn't seem to work on mac with ethernet either?

```
❯ ./discovery.py -i en12 -l debug
DEBUG:network:addrs:{18: [{'addr': '48:65:ee:18:6f:5a'}], 30: [{'addr': 'fe80::cde:6c9:a210:f0ef%en12', 'netmask': 'ffff:ffff:ffff:ffff::/64', 'flags': 1024}], 2: [{'addr': '192.168.30.107', 'netmask': '255.255.255.0', 'broadcast': '192.168.30.255'}]}
DEBUG:network:get_interface: en12 192.168.30.107 48:65:ee:18:6f:5a
Traceback (most recent call last):
  File "/Users/simonroberts/src/github/philippechataignon/smrt/./discovery.py", line 47, in <module>
    main()
  File "/Users/simonroberts/src/github/philippechataignon/smrt/./discovery.py", line 33, in main
    switches = discover_switches(args.interface)
  File "/Users/simonroberts/src/github/philippechataignon/smrt/./discovery.py", line 14, in discover_switches
    net = Network(interface)
  File "/Users/simonroberts/src/github/philippechataignon/smrt/network.py", line 64, in __init__
    self.rs.bind((Network.BROADCAST_ADDR, Network.UDP_RECEIVE_FROM_PORT))
OSError: [Errno 49] Can't assign requested address
```

**Comment by lyricnz** [comment]
I'm can't quite understand how UDP_RECEIVE_FROM_PORT/UDP_SEND_TO_PORT are supposed to be used, but I made it work on mac with the following changes

```patch
diff --git a/network.py b/network.py
index 0bfbb20..d455456 100755
--- a/network.py
+++ b/network.py
@@ -47,7 +47,7 @@ class Network:
             self.ss.settimeout(10)
         else:
             self.ss.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
-            self.ss.bind((self.ip_address, Network.UDP_RECEIVE_FROM_PORT))
+            self.ss.bind((self.ip_address, Network.UDP_SEND_TO_PORT))

         # Receiving socket
         self.rs = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
@@ -61,7 +61,7 @@ class Network:
         else:

             # Receiving socket
-            self.rs.bind((Network.BROADCAST_ADDR, Network.UDP_RECEIVE_FROM_PORT))
+            self.rs.bind(('', Network.UDP_RECEIVE_FROM_PORT))
             self.rs.settimeout(10)

     def get_interface(self, interface=None):
```


Here's the output of run:
[run.txt](https://github.com/philippechataignon/smrt/files/10334319/run.txt)

**Comment by lyricnz** [comment]
In fact there's no need to bind self.ss - that will just change which port the outgoing request uses. The switches don't care, and always reply to `Network.UDP_RECEIVE_FROM_PORT`.  So the first change in the diff can be commented out entirely.
